"""tabla states con seed idempotente

Revision ID: 00cbe98f3c48
Revises: 3a357a419009
Create Date: 2026-09-02 21:24:10.781093

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.seed_states import seed_states

# revision identifiers, used by Alembic.
revision: str = '00cbe98f3c48'
down_revision: str | Sequence[str] | None = '3a357a419009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
    seed_states(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
